sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t dockerbwong/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerbwong/docker-react npm run test
